name: Update Readme

on:
  push:
  schedule:
    - cron: "0 * * * *"

permissions: write-all

jobs:
  update-readme:
    name: Updates README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          COMMIT_MESSAGE: "Update Wakatime Weekly Activity"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_KEY }}