name: Update Wakatime Readme

on:
  push:
  schedule:
    - cron: "0 * * * *"

permissions: write-all

jobs:
  update-readme:
    name: Updates README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master 
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          SHOW_PROJECTS: "True" 
          COMMIT_MESSAGE: "Update Wakatime Weekly Activity"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_KEY }}
